### PR TITLE
#89 - Make lazy_expm analysis consistent wrt sparse/dense

### LINKED ISSUE #89: Inconsistent lazy mexp reach/check versions
The `reach` versions use the "sparse" analysis, while the `check` versions use the "dense" analysis.

@mforets: Do you see a reason for this?

### PR DESCRIPTION
**Pull request by schillic**
Closes #89.

### CODE REVIEW

**Comment by schillic** [comment]
Results for MNA5:

1D reach sparse: 593 seconds (old behavior)
1D reach dense: 697 seconds
2D check discrete sparse: 184 seconds
2D check discrete dense: 507 seconds (old behavior)

**Comment by schillic** [comment]
@mforets: I duplicated the methods and added aother option. Is this okay for you?
And should we add this option also for the other two methods (sparse and dense without lazy_expm)?

**Comment by mforets** [comment]
> @mforets: I duplicated the methods and added aother option. Is this okay for you?

okay.

> And should we add this option also for the other two methods (sparse and dense without lazy_expm)?

IIRC the current choices for the different models are already optimal, i don't think we have to add those combinations.

**Comment by schillic** [comment]
What I meant was: Should we add the parameters to the other methods? They would not have any effect. Just to avoid the inconsistency that the lazy_expm methods have an additional parameter.

**Pull request merged**
