### PR TITLE
Fix numeric type problems

### PR DESCRIPTION
**Pull request by schillic**

### CODE REVIEW

**Comment by mforets** [comment]
failing for:

```julia
julia> using Reachability
julia> A = randn(4, 4); X0 = BallInf(ones(4), 0.1)
julia> s = solve(ContinuousSystem(A, X0), :T=>0.1, :blocks=>[1,2], :apply_projection=>false);
ERROR: MethodError: no method matching reach_explicit_blocks!(::Array{Float64,2}, ::Array{LazySets.HPolygon{Float64},1}, ::Reachability.Systems.ConstantNonDeterministicInput, ::Int64, ::Int64, ::Int64, ::Reach
ability.ReachSets.##21#23{UnionAll}, ::Array{Int64,1}, ::Array{LazySets.CartesianProductArray{Float64,S} where S<:LazySets.LazySet{Float64},1})
Closest candidates are:
  reach_explicit_blocks!(::AbstractArray{NUM,2}, ::Array{S<:LazySets.LazySet{NUM},1}, ::Reachability.Systems.ConstantNonDeterministicInput, ::Int64, ::Int64, ::Int64, ::Function, ::AbstractArray{Int64,1}, ::Ar
ray{LazySets.CartesianProductArray,1}) where {NUM, S<:LazySets.LazySet{NUM}} at /Users/forets/.julia/v0.6/Reachability/src/ReachSets/reach_explicit_blocks.jl:154
  reach_explicit_blocks!(::SparseMatrixCSC{NUM,Int64}, ::Array{S<:LazySets.LazySet{NUM},1}, ::Reachability.Systems.ConstantNonDeterministicInput, ::Int64, ::Int64, ::Int64, ::Function, ::AbstractArray{Int64,1}
, ::Array{LazySets.CartesianProductArray{S<:LazySets.LazySet{NUM},S} where S<:LazySets.LazySet{S<:LazySets.LazySet{NUM}},1}) where {NUM, S<:LazySets.LazySet{NUM}} at /Users/forets/.julia/v0.6/Reachability/src/
ReachSets/reach_explicit_blocks.jl:41
  reach_explicit_blocks!(::LazySets.SparseMatrixExp{NUM}, ::Array{S<:LazySets.LazySet{NUM},1}, ::Reachability.Systems.ConstantNonDeterministicInput, ::Int64, ::Int64, ::Int64, ::Function, ::AbstractArray{Int64
,1}, ::Array{LazySets.CartesianProductArray,1}) where {NUM, S<:LazySets.LazySet{NUM}} at /Users/forets/.julia/v0.6/Reachability/src/ReachSets/reach_explicit_blocks.jl:315
  ...
Stacktrace:

 [1] #reach#19(::String, ::Float64, ::Bool, ::Bool, ::Bool, ::Type{T} where T, ::Type{T} where T, ::Bool, ::Array{Any,1}, ::Reachability.ReachSets.#reach, ::Reachability.Systems.DiscreteSystem, ::Int64) at /Us
ers/forets/.julia/v0.6/Reachability/src/ReachSets/reach.jl:139
 [2] (::Reachability.ReachSets.#kw##reach)(::Array{Any,1}, ::Reachability.ReachSets.#reach, ::Reachability.Systems.DiscreteSystem, ::Int64) at ./<missing>:0
 [3] solve(::Reachability.Systems.ContinuousSystem, ::Reachability.Options) at /Users/forets/.julia/v0.6/Reachability/src/solve.jl:127
 [4] solve(::Reachability.Systems.ContinuousSystem, ::Pair{Symbol,Float64}, ::Pair{Symbol,Array{Int64,1}}, ::Vararg{Pair{Symbol,#s56} where #s56,N} where N) at /Users/forets/.julia/v0.6/Reachability/src/solve.
jl:195
```

**Comment by mforets** [comment]
this change fixes it:

```julia
function reach_explicit_blocks!(ϕ::AbstractMatrix{NUM},
                                Xhat0::Vector{S},
                                U::ConstantNonDeterministicInput,
                                n::Int,
                                b::Int,
                                N::Int,
                                overapproximate::Function,
                                blocks::AbstractVector{Int},
                                res::Vector{CartesianProductArray{NUM}}
                               )::Void where {S<:LazySet{NUM}} where {NUM}
```

**Comment by schillic** [comment]
Good observation, I missed that.

**Comment by mforets** [comment]
err, it actually needs `CartesianProductArray{NUM}`.

**Comment by mforets** [comment]
and we need to update the methods for `check_explicit_block`(s)

**Comment by schillic** [comment]
I think this is what I did, right?

**Comment by mforets** [comment]
there is one issue in the check blocks:

```julia
julia> s = solve(ContinuousSystem(A, X0), :T=>0.1, :mode=>"check", :blocks=>[1],
                 :property=>LinearConstraintProperty([1., -1.], 2.))
ERROR: MethodError: Cannot `convert` an object of type Array{LazySets.LazySet,1} to an object of type LazySets.MinkowskiSumArray
This may have arisen from a call to the constructor LazySets.MinkowskiSumArray(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] check_explicit_block!(::Array{Float64,2}, ::Array{LazySets.HPolygon{Float64},1}, ::Reachability.Systems.ConstantNonDeterministicInput, ::Reachability.Properties.##21#23{UnionAll}, ::Int64, ::Int64, ::Int6

4, ::Int64, ::Reachability.Properties.LinearConstraintProperty{Float64}) at /Users/forets/.julia/v0.6/Reachability/src/Properties/check_explicit_block.jl:148
 [2] #check_property#19(::String, ::Float64, ::Bool, ::Bool, ::Bool, ::Type{T} where T, ::Bool, ::Array{Any,1}, ::Reachability.Properties.#check_property, ::Reachability.Systems.DiscreteSystem, ::Int64) at /Us
ers/forets/.julia/v0.6/Reachability/src/Properties/check_property.jl:142
 [3] (::Reachability.Properties.#kw##check_property)(::Array{Any,1}, ::Reachability.Properties.#check_property, ::Reachability.Systems.DiscreteSystem, ::Int64) at ./<missing>:0
 [4] solve(::Reachability.Systems.ContinuousSystem, ::Reachability.Options) at /Users/forets/.julia/v0.6/Reachability/src/solve.jl:167
 [5] solve(::Reachability.Systems.ContinuousSystem, ::Pair{Symbol,Float64}, ::Pair{Symbol,String}, ::Vararg{Pair{Symbol,#s56} where #s56,N} where N) at /Users/forets/.julia/v0.6/Reachability/src/solve.jl:195
```

**Comment by schillic** [comment]
I see, this is the same problem, i can fix it similarly.

**Pull request merged**
