### PR TITLE
#111 - Fix slowdowns with sparse models and 1D blocks

### LINKED ISSUE #111: Investigate slowdowns with sparse models and 1D blocks
| Model | 2D Hyperrectangle | 1D Hyperrectangle | 1D Interval |
| -- | -- | -- | -- |
| ISS | 1.94 | 5.47 | 5.93 |
| FOM | 6.64 | 36 | 37 |

(runtimes in seconds)

### PR DESCRIPTION
**Pull request by schillic**
Closes #111.

### CODE REVIEW

**Comment by schillic** [comment]
Benchmark results for ISS (in seconds):

| branch | 1D Interval | 1D Hyperrectangle | 2D Hyperrectangle |
|-|-|-|-|
| master | 8.67 | 8.73 | 2.80 |
| this | 1.32 | 1.33 | 2.62 |

A benchmark for Beam (dense model) showed no difference.

**Comment by schillic** [comment]
Property checking results for ISS (violation at step 3528, 135 variables involved, in seconds):

| 1D Interval | 1D Hyperrectangle | 2D Hyperrectangle |
|-|-|-|
| 17.04 | 17.78 | 23.24 |

**Comment by mforets** [comment]
that's very cool, how you found the optimal partition representation for 1D or kD blocks 👍

> A benchmark for Beam (dense model) showed no difference.

there we don't use `findfirst`.

**Comment by schillic** [comment]
>>    A benchmark for Beam (dense model) showed no difference.
>
> there we don't use findfirst.

What I wanted to say was: The new partition representation does not have negative consequences.

**Comment by schillic** [comment]
I will remove the two "indentation" commits and do them after the merge.

**Pull request merged**
