### PR TITLE
#52 - Use lazy SymmetricIntervalHull

### LINKED ISSUE #52: Use lazy SymmetricIntervalHull

### PR DESCRIPTION
**Pull request by mforets**
Closes #52.

this is a WIP that has in it the option passed to `discretize`, but needs to add `lazy_sih` as a valid option for the interface.

### CODE REVIEW

**Comment by schillic** [comment]
Should I take over and add the option?

**Comment by mforets** [comment]
> Should I take over and add the option?

ok!

**Comment by schillic** [comment]
Done (I also rebased such that the fixes in `master` are visible and the unit tests pass).

**Comment by mforets** [comment]
well done. have you tried if this option is usable from `solve`?

**Comment by schillic** [comment]
> have you tried if this option is usable from solve?

Yes :)

**Comment by mforets** [comment]
thanks (i coulnd't test because my actual version of lazysets had `sfarray` updated and there were unrelated errors)

**Comment by mforets** [comment]
> thanks (i coulnd't test because my actual version of lazysets had sfarray updated and there were unrelated errors)

continued in #70

**Pull request merged**
