### PR TITLE
#194 - Add option to use template directions for overapproximation

### LINKED ISSUE #194: Add option to use template directions for overapproximation
Add a new option `:template_directions` to specify using template directions for overapproximation.

At some point, we may want to revise the way a user chooses the overapproximation.

### PR DESCRIPTION
**Pull request by schillic**
Closes #194.

### CODE REVIEW

**Comment by schillic** [comment]
Example:
```julia
julia> using Reachability, Plots

julia> A = [0.366175  0.69602    0.561862  0.542789
            0.928728  0.23207    0.689857  0.914719
            0.460298  0.730495   0.655784  0.855397
            0.701141  0.0800105  0.283488  0.572829]; X0 = BallInf(ones(4), 0.1);

julia> s1 = solve(ContinuousSystem(A, X0), :T=>0.1, :partition=>[1:2, 3:4],
                 :vars=>[1,2], :ε_proj => 1e-5);

julia> s2 = solve(ContinuousSystem(A, X0), :T=>0.1, :partition=>[1:2, 3:4],
                 :vars=>[1,2], :ε_proj => 1e-5, :template_directions => :oct);

julia> s3 = solve(ContinuousSystem(A, X0), :T=>0.1, :partition=>[1:2, 3:4],
                 :vars=>[1,2], :ε => 1e-5);

julia> plot(s1); plot!(s2); plot!(s3, opacity=0.1)
```

plot legend: rectangles (blue), octagons (red), epsilon-close polygons (green)
octagons

**Comment by mforets** [comment]
Using a bigger partition, there are also boxes, even with `:oct` template directions. Also tried with `:boxdiag`. Is it correct?

```julia
julia> s4 = solve(ContinuousSystem(A, X0), :T=>0.1, :partition=>[1:4],
                            :vars=>[1,2], :template_directions => :oct);

julia> plot(s4, opacity=0.1)
```

screen shot 2018-05-21 at 15 41 19

**Comment by mforets** [comment]
However for 

```julia
julia> s5 = solve(ContinuousSystem(A, X0), :T=>0.1, :partition=>[1:4],
               :vars=>[1,2], :template_directions => :oct, :ε => 1e-5);

julia> plot(s5, opacity=0.1)
```
screen shot 2018-05-21 at 15 44 11


What is `:ε => 1e-5` actually doing, is this #196 ?

**Comment by schillic** [comment]
> What is :ε => 1e-5 actually doing [...]?

This is used for the projection precision. If not specified, the projection uses `set_type`, which defaults to `Hyperrectangle`. Alternatively, it would be sufficient to use `:ε_proj`.
Do you have an idea how to do this automatically (maybe in #196)?

**Comment by mforets** [comment]
Ok, makes sense.

**Pull request merged**
