### PR TITLE
Optim import needed in v0.7

### PR DESCRIPTION
**Pull request by mforets**
Optim using is needed in the tests v0.7 

(this is a minimal change; we could otherwise run the `using Optim` inside the functions that need it inside Reachability, but then that's just about the same of adding this package as a requrement for LazySets, no?)

### CODE REVIEW

**Comment by schillic** [comment]
[`Optim` is already in `REQUIRE`](https://github.com/JuliaReach/Reachability.jl/blob/master/REQUIRE#L8), so this should not be necessary unless we need it in the scripts (which I doubt), right?

**Comment by mforets** [comment]
Correct, and it is used in the `ReachSets` module. I don't know why does this error occur (which doesn't happen in v0.6..). Let me add v0.7 in the build script to check the error in the CI.

**Comment by mforets** [comment]
- in the v0.6 build there is a failure, `LazySets is not a git repository` ??

- in the v0.7 build one gets the error that i wanted to address in this PR; see [this line](https://travis-ci.org/JuliaReach/Reachability.jl/jobs/455401927#L916)

**Comment by schillic** [comment]
> in the v0.6 build there is a failure, LazySets is not a git repository ??

Saw it, new try...

> in the v0.7 build one gets the error that i wanted to address in this PR; see this line

I saw that in `LazySets` we also `Pkg.add("Optim")`. I guess that the newer Julia versions rather want to use the `Project` files, so `REQUIRE` seems to be ignored there.

**Comment by schillic** [comment]
Here is the real problem:
```julia
julia> using Reachability

julia> LazySets
LazySets

julia> Optim
ERROR: UndefVarError: Optim not defined
```
So since we only have `using Optim` in `Reachability.ReachSets`, it seems to not get imported to `Reachability`. So I would say that we have to add `using Optim` to `Reachability.jl`. Let me try.

**Comment by schillic** [comment]
I identified the problem. It is in `LazySets`. We have `@assert isdefined(Main, :Optim)`, but we are not actually requiring module `Main` but just the current context. From `Reachability` for instance we are in module `Reachability` (who would have guessed). If you comment this assertion, everything works. So we have to find out what we have to write instead of `Main`...

**Comment by mforets** [comment]
the following should works if we use `@reexport`, 

```julia
julia> using Reachability

julia> LazySets
LazySets

julia> Optim
Optim
```

however it has not been the idea to use `reexport` the module `Optim` from `Reachability`.

> We have @assert isdefined(Main, :Optim)

👍  

i have tried with `@eval using Optim` inside `Reachability.jl` and `ReachSets.jl` module but it doesn't work either.

**Comment by schillic** [comment]
Yes, forget about the first part, that was just a red herring.

**Comment by mforets** [comment]
is it `@assert isdefined(@__MODULE__`, :Optim)` ?

```julia
help?> @__MODULE__
  @__MODULE__ -> Module

  Get the Module of the toplevel eval, which is the Module code is currently being read from.
```

**Comment by schillic** [comment]
Yes! :tada: :100: :crown: :trophy:

**Pull request merged**
