### PR TITLE
fix: throw error when options contain invalid symbol

### PR DESCRIPTION
**Pull request by schillic**

### CODE REVIEW

**Comment by mforets** [comment]
Looks good, tested in `helicopter` example. Could you add this to the error message:

> Unrecognized option 'block' found. See `Reachability.G_available_keywords.dict` for all valid keywords.

what does `G` stand for?

**Comment by schillic** [comment]
"global", but you are right, it is no global variable, only visible inside this file.
Should we have a naming convention for this?

**Comment by schillic** [comment]
The problem is that this set is filled dynamically, so you cannot see it (unless we add it to the output).

**Comment by mforets** [comment]
`availble_keywords` should be ok. the user can check exported objects with `names(Reachability)`.

> The problem is that this set is filled dynamically, so you cannot see it (unless we add it to the output).

for me it prints this:

```julia
> Reachability.G_available_keywords.dict
Dict{Symbol,Void} with 23 entries:
  :property                  => nothing
  :n                         => nothing
  :blocks                    => nothing
  :assume_sparse             => nothing
  :apply_projection          => nothing
  :ε                         => nothing
  :coordinate_transformation => nothing
  :plot_vars                 => nothing
  :algorithm                 => nothing
  :iterative_refinement      => nothing
  :assume_homogeneous        => nothing
  :output_variables          => nothing
  :mode                      => nothing
  :N                         => nothing
  :sampling_time             => nothing
  :time_horizon              => nothing
  :lazy_expm                 => nothing
  :approx_model              => nothing
  :δ                         => nothing
  :T                         => nothing
  :projection_matrix         => nothing
  :pade_expm                 => nothing
  :lazy_X0                   => nothing
```

**Comment by schillic** [comment]
Oh, so it *is* global 👍
Note that this only works after running, so from the REPL.
You cannot output this set statically.

**Pull request merged**
