### PR TITLE
#131 - Add option to control number of threads used by OpenBLAS

### LINKED ISSUE #131: Add option to control number of threads used by OpenBLAS
Even though we currently do not use parallel computing features, Julia often uses all my four cores. We should understand why.

I observed it during discretization, decomposition, and image computation for dense matrices (but not for sparse matrices). First guess: dense matrix multiplication (Julia internal)

### PR DESCRIPTION
**Pull request by schillic**
Closes #131.

I tested that one can safely use values greater than supported by the CPU.

### CODE REVIEW

**Comment by mforets** [comment]
i suggest to not change the default, whose value can be obtained by calling:

```julia
# 
# This function is a part of Julia. License is MIT: https://julialang.org/license
#
const get_num_threads = function() # anonymous so it will be serialized when called
    blas = LinearAlgebra.BLAS.vendor()
    # Wrap in a try to catch unsupported blas versions
    try
        if blas == :openblas
            return ccall((:openblas_get_num_threads, Base.libblas_name), Cint, ())
        elseif blas == :openblas64
            return ccall((:openblas_get_num_threads64_, Base.libblas_name), Cint, ())
        elseif blas == :mkl
            return ccall((:MKL_Get_Max_Num_Threads, Base.libblas_name), Cint, ())
        end

        # OSX BLAS looks at an environment variable
        if Sys.isapple()
            return ENV["VECLIB_MAXIMUM_THREADS"]
        end
    end

    return nothing
end
```

**Comment by mforets** [comment]
the other valid approach would be to change `set_num_threads` if this option is passed as argument, and do nothing otherwise.

**Comment by schillic** [comment]
> the other valid approach would be to change set_num_threads if this option is passed as argument, and do nothing otherwise.

The problem is that if you use this option once, you cannot reset it anymore. So we probably have to copy this function.

**Comment by schillic** [comment]
We decided to only have a note in the manual (see #134).

**Pull request closed without merging**
