### PR TITLE
use AbstractVector and AbstractMatrix whenever possible

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by schillic** [comment]
Looks good.

I was first thinking that we could simplify `Union{AbstractMatrix{Float64}, SparseMatrixExp}`, but `SparseMatrixExp` is not a "normal" `AbstractMatrix`.
Does it make sense to make it one? I neither know the implications nor the benefit.

Another thought: Should we parameterize `SparseMatrixExp{Float64}`?

**Comment by mforets** [comment]
>  Does it make sense to make it one? I neither know the implications nor the benefit.

you raise a good point. the discussion [is taking place on a TODO list in Expokit, issue #9](https://github.com/acroy/Expokit.jl/issues/9). i think the short answer is now to maintain `SparseMatrixExp`, since we only have methods to lookup row/column and that's enough in our application. 

> Another thought: Should we parameterize SparseMatrixExp{Float64}?

yes, seems like sth that should be there, let me add that.

**Comment by schillic** [comment]
>  let me add that.

Okay, we can also merge and add an issue for later, whatever you prefer.

**Comment by mforets** [comment]
ok i think i've got all of them. i guess this will also require me to adapt LazySets.

**Comment by schillic** [comment]
In `Utils.jl` we also have `Union{Matrix{Float64}, SparseMatrixCSC{Float64, Int64}` twice which we could merge.

**Comment by schillic** [comment]
There are a lot of warnings and one failing test!

**Comment by mforets** [comment]
we're fine! i double checked that Travis build was green with this patch, although this site didn't refresh and kept the red badge. I guess there is a little lag of 5..10 minutes or so.

**Comment by schillic** [comment]
Okay, I also checked locally 👍

**Pull request merged**
