### PR TITLE
#12 - :plot_vars and :blocks handling

### PR DESCRIPTION
**Pull request by schillic**
@mforets: Please check if this is what you had in mind.
More comments in the [related issue](https://github.com/JuliaReach/Reachability.jl/issues/12).

### CODE REVIEW

**Comment by mforets** [comment]
i think this what we discussed. the remaining thing would be that we add a couple of calls for the different expected use cases in the `/tests` parts.

**Comment by mforets** [comment]
> the remaining thing would be that we add a couple of calls for the different expected use cases in the /tests parts.

... i can continue with that

**Comment by schillic** [comment]
Thanks. Note that this PR is older than the discussion and I remember that we diverged.

**Comment by mforets** [comment]
This is superseded by #85.

**Pull request closed without merging**
