### PR TITLE
Update unit_solve_hybrid_bouncing_ball.jl

### LINKED ISSUE #80: merge(op1::Options, opn::Options...) modifies the first argument
Provide two functions:
1. `merge` should make a copy of the dictionary and not modify the first argument.
2. `merge!` should modify the options and return the first argument.

### PR DESCRIPTION
**Pull request by mforets**
Closes #80.

- [x] some cleanup in the test script
- [x] add `copy` method for options
- [x] revise `merge!` and `merge` methods
- [ ] ~~fix issue `MethodError: no method matching start(::LazySets.HPolyhedron{Float64})` << needs subset check~~

### CODE REVIEW

**Comment by mforets** [comment]
but one expects that the copy is done inside `solve` (compared to `solve!`)

**Comment by schillic** [comment]
You are welcome to fix #80.

**Comment by schillic** [comment]
`LoadError: LoadError: MethodError: no method matching merge!(::Dict{Symbol,Any}, ::Dict{Symbol,Any})
  You may have intended to import Base.merge!`

**Comment by mforets** [comment]
Thanks. Now tests pass locally.

**Pull request merged**
