### PR TITLE
revise Transformations

### PR DESCRIPTION
**Pull request by schillic**
- overhaul of `Transformations.jl`, most notably:
  * also support `ContinuousSystem`s
  * change argument order
- added documentation

### CODE REVIEW

**Comment by mforets** [comment]
Should we add a `export Transformations` statement in the main module `Reachability.jl`?

**Comment by mforets** [comment]
should we have default transformation method?

```julia
function transform(S::T,
                   method::String="schur")::Tuple{T, SparseMatrixCSC{Float64, Int64}} where
                       {T<:Union{DiscreteSystem, ContinuousSystem}}
...
```

**Comment by mforets** [comment]
also, we don't need to cast the result as a sparse matrix anymore. so the signature could be:

```julia
function transform(S::T,
                   method::String="schur")::Tuple{T, AbstractMatrix{N}} where
                       {T<:Union{DiscreteSystem, ContinuousSystem}} where{N<:Number}
    if method == "schur"
        (A, X0, U, M) = transform_schur(S)
    else
        error("the transformation method $method is not defined")
    end

    if S isa DiscreteSystem
        return (DiscreteSystem(A, X0, S.δ, U), M)
    else
        return (ContinuousSystem(A, X0, U), M)
    end
end
```

**Comment by mforets** [comment]
while on this i realized there's no such `jordan` command available ([asked in discourse](https://discourse.julialang.org/t/jordan-form-of-a-matrix/7123)). hence i'll remove that part that i planned to add in this branch, for later.

**Comment by schillic** [comment]
I forgot the status here, should we merge?

**Comment by mforets** [comment]
yes

**Pull request merged**
