### PR TITLE
WIP #275 - Low-dimensional discrete-post operator

### PR DESCRIPTION
**Pull request by kpotomkin**
screen shot 2019-01-25 at 12 17 36 am
Description:
We run 2 Continuous_Post analysis (i) on all variables and (ii)on only necessary vars from our locations (which we get from constrained dimension function), do all intersections in low-dimension first and only if the result is non-empty we run intersection in full dimension.

### CODE REVIEW

**Comment by mforets** [comment]
Shouldn't the low-dims idea be an option for the intersection algorithm on the first place? This option can be passed around to a solver, existing or not.

**Comment by kostakoida** [comment]
> JuliaReach/LazySets.jl#1041

I have added LazySets-based algorithm to the issue you mentioned above.

**Comment by mforets** [comment]
In lines 7 and 8, depending on the block decomposition used one may be able to re-use the reach sets from 7 into 8, or project them. This will be cheaper than computing the reach set again in other variables, i think.

**Comment by mforets** [comment]
i don't understand line 11: seems like it can be pulled out of the `for` loop.

**Comment by kostakoida** [comment]
> In lines 7 and 8, depending on the block decomposition used one may be able to re-use the reach sets from 7 into 8, or project them. This will be cheaper than computing the reach set again in a subset of the variables, i think.

Sounds good for me, I will make appropriate changes and update the file. 

> i don't understand line 11: seems like it can be pulled out of the `for` loop.

Yes, you`re right. Either way it should be `push!(res, (R_h[i], loc))`

**Comment by mforets** [comment]
could you outsource the example to a separate PR?

**Pull request closed without merging**
