### PR TITLE
#371 - Deprecation warning with tic - tocc

### LINKED ISSUE #371: Deprecation warning with tic - tocc
the tic-toq construction is deprecated in v0.7/1.0 (see #361); in Reachability it is used to pass runtime information to the logger:

```julia
...
        tic()
        (system, transformation_matrix) =
            transform(system, options[:coordinate_transformation])
        tocc()
...
# tocc information is passed to the logger
@inline function tocc(func::Function=info)
    func("elapsed time: $(toq()) seconds")
end
```

an approach (idk if it's the only one) could be:

```julia
Δtₑ = @elapsed begin
        (system, transformation_matrix) =
            transform(system, options[:coordinate_transformation])
end
tocc(Δtₑ)

@inline function tocc(Δtₑ, func::Function=info)
    func("elapsed time: $(Δtₑ) seconds")
end
```

### LINKED ISSUE #408: Update info macro
In v0.7

```julia
julia> info("abcde")
┌ Warning: `info()` is deprecated, use `@info` instead.

│   caller = top-level scope at none:0
└ @ Core none:0
INFO: abcde
```

In v1.0.2

```julia
julia> info("abcde")
ERROR: UndefVarError: info not defined
Stacktrace:
 [1] top-level scope at none:0

julia> @info("abcde")
[ Info: abcde
```

### PR DESCRIPTION
**Pull request by schillic**
Closes #371.
Closes #408.

I am not too happy with the output format, but I find it acceptable:
```julia
elapsed time: 7.152557373046875e-6 seconds
```
But I did not find an easy way to control that.
There is [`@printf`](https://stackoverflow.com/questions/24580334/jula-repl-number-formatting#24593139), but this requires another (standard) package.

### CODE REVIEW

**Comment by mforets** [comment]
Does `round` help?

```julia
julia> t0 = time(); sleep(0.5); t1 = time(); t1-t0
0.5045578479766846

julia> round(t1-t0, digits=3)
0.505
```

**Comment by schillic** [comment]
There is a problem with `round`: In v0.6, this function did not take keyword arguments. This is supported via `Compat`, but we load `compat.jl` only from the submodules. `logging.jl` resides in the main module. So just adding `import Compat.round` to `compat.jl` does not help because this file is never read from the main module. We can load `compat.jl` from the main module, but then i get this:
```julia
WARNING: using Utils._A_mul_B! in module Reachability conflicts with an existing identifier.
WARNING: using Utils._At_mul_B in module Reachability conflicts with an existing identifier.
WARNING: using ReachSets._A_mul_B! in module Reachability conflicts with an existing identifier.
WARNING: using ReachSets._At_mul_B in module Reachability conflicts with an existing identifier.
WARNING: using Transformations._A_mul_B! in module Reachability conflicts with an existing identifier.
WARNING: using Transformations._At_mul_B in module Reachability conflicts with an existing identifier.
```
However, in `LazySets` it looks to me that we do it in the same way :thinking:

For now I used `Compat.round` in the code, but this is not a nice solution.

**Comment by mforets** [comment]
> We can load compat.jl from the main module, but then i get this:

Perhaps because of the `@reexport`,

```julia
@reexport using Reachability.Utils,
                Reachability.ReachSets,
                Reachability.Transformations
```

In LazySets, `Approximations` is not reexported; only the module's name is exported.

**Comment by mforets** [comment]
[The issue #408](https://github.com/JuliaReach/Reachability.jl/issues/408) is related to this one.

**Pull request merged**
